---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkinspv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /mnt/data
  storageClassName: manual
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node01

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jenkins
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
          app: jenkins
    spec:
      containers:
      - image: jenkins/jenkins:lts-jdk11
        name: jenkins
        ports:
        - containerPort: 8080
          protocol: TCP
        
        volumeMounts:
            - name: jenkins-storage
              mountPath: /var/jenkins_home 
      volumes:
      - name: jenkins-storage
        persistentVolumeClaim:
          claimName: jenkins-storage-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-storage-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
     requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
        name: jenkins-service
spec:
  type: NodePort      
  selector:
          app: jenkins
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32008
